import { ItsMyConfigPlaceholder } from "./itsmyconfig";

export const DEFAULT_PLACEHOLDERS: ItsMyConfigPlaceholder[] = [
  {
    id: 'server-name',
    description: 'Main server brand shown in messages.',
    type: 'colored_text',
    value: '<gradient:#ff0f7b:#f89b29><bold>ServerName</bold></gradient>',
  },
  {
    id: 'prefix',
    description: 'Shared prefix used in chat notifications.',
    type: 'string',
    value: '<p:server-name> <p:text-color>┃',
  },
  {
    id: 'error-prefix',
    description: 'Prefix used for error messages.',
    type: 'string',
    value: '<red><bold>ERROR</bold></red> <p:text-color>┃',
  },
  {
    id: 'primary-color',
    description: 'Main accent color.',
    type: 'color',
    value: 'yellow',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'secondary-color',
    description: 'Secondary accent color.',
    type: 'color',
    value: 'gold',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'text-color',
    description: 'Default readable text color.',
    type: 'color',
    value: 'white',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'dark-color',
    description: 'Muted helper color.',
    type: 'color',
    value: 'gray',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'darkest-color',
    description: 'Smallest contrast helper color.',
    type: 'color',
    value: 'dark_gray',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'discord',
    description: 'Discord invite, without https://.',
    type: 'string',
    value: 'discord.gg/example',
  },
  {
    id: 'store',
    description: 'Store domain, without https://.',
    type: 'string',
    value: 'store.servername.net',
  },
  {
    id: 'ip',
    description: 'Server IP shown in menus and tablist.',
    type: 'string',
    value: 'play.servername.net',
  },
  {
    id: 'exp-format',
    description: 'EXP amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#F15BB5>{0}◎</#F15BB5>',
  },
  {
    id: 'eco-format',
    description: 'Economy amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<yellow>{0}⛁</yellow>',
  },
  {
    id: 'price-modifier',
    description: 'Math expression used to rescale prices. `{0}` is amount.',
    type: 'math',
    value: '1*{0}',
    rounding: 'HALF_UP',
    precision: 1,
  },
];


export const HYPIXEL_PLACEHOLDERS: ItsMyConfigPlaceholder[] = [
  {
    id: 'server-name',
    description: 'Main server brand shown in messages.',
    type: 'colored_text',
    value: '<#30c67c>[HYPIXEL]</#30c67c>',
  },
  {
    id: 'prefix',
    description: 'Shared prefix used in chat notifications.',
    type: 'string',
    value: '<p:server-name> <dark_gray>➢</dark_gray><p:text-color>',
  },
  {
    id: 'error-prefix',
    description: 'Prefix used for error messages.',
    type: 'string',
    value: '<red>[ERROR]</red> <dark_gray>➢</dark_gray><p:text-color>',
  },
  {
    id: 'primary-color',
    description: 'Main accent color.',
    type: 'color',
    value: '#8de9d5',
    bold: false,
    italic: false,
    underlined: true,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'secondary-color',
    description: 'Secondary accent color.',
    type: 'color',
    value: '#85FFA9',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'text-color',
    description: 'Default readable text color.',
    type: 'color',
    value: '#ECFFF6',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'dark-color',
    description: 'Muted helper color.',
    type: 'color',
    value: '#ADB8B3',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'darkest-color',
    description: 'Smallest contrast helper color.',
    type: 'color',
    value: '#4A695A',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'discord',
    description: 'Discord invite, without https://.',
    type: 'string',
    value: 'discord.gg/hypixel',
  },
  {
    id: 'store',
    description: 'Store domain, without https://.',
    type: 'string',
    value: 'store.hypixel.net',
  },
  {
    id: 'ip',
    description: 'Server IP shown in menus and tablist.',
    type: 'string',
    value: 'play.hypixel.net',
  },
  {
    id: 'exp-format',
    description: 'EXP amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#F15BB5>{0}◎</#F15BB5>',
  },
  {
    id: 'eco-format',
    description: 'Economy amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#FFCF9C>${0}</#FFCF9C>',
  },
  {
    id: 'price-modifier',
    description: 'Math expression used to rescale prices. `{0}` is amount.',
    type: 'math',
    value: '2*{0}',
    rounding: 'HALF_UP',
    precision: 1,
  },
];

export const ORIGIN_REALMS_PLACEHOLDERS: ItsMyConfigPlaceholder[] = [
  {
    id: 'server-name',
    description: 'Main server brand shown in messages.',
    type: 'colored_text',
    value: '<smallcaps><#d4acfb>OriginRealms</#d4acfb></smallcaps>',
  },
  {
    id: 'prefix',
    description: 'Shared prefix used in chat notifications.',
    type: 'string',
    value: '<p:server-name> <gray>»</gray><p:text-color><smallcaps>',
  },
  {
    id: 'error-prefix',
    description: 'Prefix used for error messages.',
    type: 'string',
    value: '<smallcaps><red>Error</red> <gray>»</gray><p:text-color>',
  },
  {
    id: 'primary-color',
    description: 'Main accent color.',
    type: 'color',
    value: '#8364e8',
    bold: false,
    italic: true,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'secondary-color',
    description: 'Secondary accent color.',
    type: 'color',
    value: '#F85BBC',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'text-color',
    description: 'Default readable text color.',
    type: 'color',
    value: '#FBE9FF',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'dark-color',
    description: 'Muted helper color.',
    type: 'color',
    value: '#B6A7AC',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'darkest-color',
    description: 'Smallest contrast helper color.',
    type: 'color',
    value: '#403044',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'discord',
    description: 'Discord invite, without https://.',
    type: 'string',
    value: 'discord.gg/originrealms',
  },
  {
    id: 'store',
    description: 'Store domain, without https://.',
    type: 'string',
    value: 'store.originrealms.net',
  },
  {
    id: 'ip',
    description: 'Server IP shown in menus and tablist.',
    type: 'string',
    value: 'play.originrealms.net',
  },
  {
    id: 'exp-format',
    description: 'EXP amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#F15BB5>{0}◎</#F15BB5>',
  },
  {
    id: 'eco-format',
    description: 'Economy amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#EB7B9D>$<italic>{0}</italic></#EB7B9D>',
  },
  {
    id: 'price-modifier',
    description: 'Math expression used to rescale prices. `{0}` is amount.',
    type: 'math',
    value: '0.75*{0}',
    rounding: 'HALF_UP',
    precision: 1,
  },
];

export const THE_HIVE_PLACEHOLDERS: ItsMyConfigPlaceholder[] = [
  {
    id: 'server-name',
    description: 'Main server brand shown in messages.',
    type: 'colored_text',
    value: '<gradient:#ff930f:#fff95b>TheHive</gradient>',
  },
  {
    id: 'prefix',
    description: 'Shared prefix used in chat notifications.',
    type: 'string',
    value: '<gray>[<p:server-name>]</gray><p:text-color>',
  },
  {
    id: 'error-prefix',
    description: 'Prefix used for error messages.',
    type: 'string',
    value: '<gray>[<red>Error</red>]</gray><p:text-color>',
  },
  {
    id: 'primary-color',
    description: 'Main accent color.',
    type: 'color',
    value: '#FDC83B',
    bold: true,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'secondary-color',
    description: 'Secondary accent color.',
    type: 'color',
    value: '#44EFF8',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'text-color',
    description: 'Default readable text color.',
    type: 'color',
    value: '#FFF3CD',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'dark-color',
    description: 'Muted helper color.',
    type: 'color',
    value: '#90876D',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'darkest-color',
    description: 'Smallest contrast helper color.',
    type: 'color',
    value: '#332F23',
    bold: false,
    italic: false,
    underlined: false,
    strikethrough: false,
    obfuscated: false,
  },
  {
    id: 'discord',
    description: 'Discord invite, without https://.',
    type: 'string',
    value: 'discord.gg/thehive',
  },
  {
    id: 'store',
    description: 'Store domain, without https://.',
    type: 'string',
    value: 'store.thehive.net',
  },
  {
    id: 'ip',
    description: 'Server IP shown in menus and tablist.',
    type: 'string',
    value: 'play.thehive.net',
  },
  {
    id: 'exp-format',
    description: 'EXP amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#F15BB5>{0}◎</#F15BB5>',
  },
  {
    id: 'eco-format',
    description: 'Economy amount format. `{0}` is amount.',
    type: 'colored_text',
    value: '<#0082D3>$<bold>{0}</bold></#0082D3>',
  },
  {
    id: 'price-modifier',
    description: 'Math expression used to rescale prices. `{0}` is amount.',
    type: 'math',
    value: '1.5*{0}',
    rounding: 'HALF_UP',
    precision: 1,
  },
];